### ISSUE TITLE
Trying to read 4 bytes beyond buffer end

### ISSUE THREAD

**Issue by wkoszek** [suyashkumar/dicom#63] opened 2020-04-21 19:41 UTC
Another issue resulting from a scan around several millions of DICOMs. We have to dig deeper around what is causing that.

**Comment by IChocked** [comment] 2020-05-29 22:42
@suyashkumar Found some example files for this error

[issue63.zip](https://github.com/suyashkumar/dicom/files/4704667/issue63.zip)

Data Citation:
_Kinahan, Paul; Muzi, Mark; Bialecki, Brian; Coombs, Laura. (2017). Data from ACRIN-FLT-Breast. The Cancer Imaging Archive. http://doi.org/10.7937/K9/TCIA.2017.ol20zmxg_

**Comment by suyashkumar** [comment] 2020-11-01 05:37
Closing this out as I'm unable to reproduce it with the current `s/1.0-rewrite` branch candidate!

**Closed by suyashkumar** 2020-11-01 05:37 UTC
