### ISSUE TITLE
error wrap in readTag function

### ISSUE THREAD

**Issue by luxsa** [suyashkumar/dicom#179] opened 2021-01-21 03:12 UTC
### When wrap an error, it's better to use %w than %v

> My code

```go
func readTag(r dicomio.Reader) (*tag.Tag, error) {
	group, gerr := r.ReadUInt16()
	if gerr != nil {
		return nil, fmt.Errorf("error reading group tag: %w", gerr)
	}
	element, eerr := r.ReadUInt16()
	if eerr != nil {
		return nil, fmt.Errorf("error reading element tag: %w", eerr)
	}
	return &tag.Tag{Group: group, Element: element}, nil
}
```

**Comment by suyashkumar** [comment] 2021-01-21 06:33
+1 I agree and think we need to go back through the library and add in support for wrapped errors (see the existing issue I opened to track this: #174). Going to close this as a duplicate of that issue. Thank you!

**Closed by suyashkumar** 2021-01-21 06:33 UTC
